name: Go CI

on:
  push:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-ci.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-ci.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Verify modules tidy
        run: |
          timeout -k 30s -s SIGKILL 30s go mod tidy
          timeout -k 30s -s SIGKILL 30s git diff --exit-code

      - name: Go fmt check
        run: |
          timeout -k 60s -s SIGKILL 60s go fmt ./...
          timeout -k 30s -s SIGKILL 30s git diff --exit-code

      - name: Build
        run: timeout -k 120s -s SIGKILL 120s go build ./...

      - name: Vet
        run: timeout -k 120s -s SIGKILL 120s go vet ./...

      - name: Test (race)
        run: timeout -k 300s -s SIGKILL 300s go test ./... -v -race -count=1
